#pragma once

#include <ninecraft/android/android_string.h>
#include <ninecraft/android/android_vector.h>
#include <ninecraft/gfx/textures.h>
#include <stdbool.h>

typedef struct {
    char *data;
    int size;
} minecraft_asset_t;

typedef union {
    struct {
        android_string_gnu_t unknown0;
        android_string_gnu_t unknown1;
        android_string_gnu_t unknown2;
        android_string_gnu_t unknown3;
    } gnu;
    struct {
        android_string_stlp_t unknown0;
        android_string_stlp_t unknown1;
        android_string_stlp_t unknown2;
        android_string_stlp_t unknown3;
    } stlp;
} minecraft_login_info_t;

typedef struct {
    void **vtable;
    unsigned char is_keyboard_hidden;
    void *u0;
    void *u1;
    void *u2;
    void *u3;
    void *u4;
    void *u5;
    char filler[0x100];
} app_platform_0_9_0_t;

typedef struct {
    void (*__destroy0)(void *__this);
    void (*__destroy1)(void *__this);
    void (*onImagePickingSuccess)(void *__this, android_string_t *resource_path);
    void (*onImagePickingCanceled)(void *__this);
} image_picking_callback_vtable_0_11_0_t;

typedef struct {
    image_picking_callback_vtable_0_11_0_t *vtable;
} image_picking_callback_0_11_0_t;

typedef struct {
    void (*__destroy0)(void *__this);
    void (*__destroy1)(void *__this);
    void (*saveScreenshot)(void *__this, android_string_t *resource_path, int width, int height);
    android_string_t (*getImagePath)(void *__this, android_string_t *resource_path, bool is_full);
    void (*loadPNG)(void *__this, image_data_0_9_0_t *image, android_string_t *resource_path, bool alpha);
    void (*loadTGA)(void *__this, image_data_0_9_0_t *image, android_string_t *resource_path);
    void (*playSound)(void *__this, android_string_t *resource_path, float volume, float pitch);
    void (*showDialog)(void *__this, int dialog_id);
    void (*createUserInput)(void *__this);
    int (*getUserInputStatus)(void *__this);
    android_vector_t (*getUserInput)(void *__this);
    android_string_t (*getDateString)(void *__this, int ms);
    int (*checkLicense)(void *__this);
    bool (*hasBuyButtonWhenInvalidLicense)(void *__this);
    void (*uploadPlatformDependentData)(void *__this, int length, void *data);
    minecraft_asset_t (*readAssetFile)(void *__this, android_string_t *resource_path);
    void (*_tick)(void *__this);
    int (*getScreenWidth)(void *__this);
    int (*getScreenHeight)(void *__this);
    float (*getPixelsPerMillimeter)(void *__this);
    bool (*isNetworkEnabled)(void *__this, bool set);
    void (*openLoginWindow)(void *__this);
    bool (*isPowerVR)(void *__this);
    int (*getKeyFromKeyCode)(void *__this, int code, int meta, int dev_id);
    void (*buyGame)(void *__this);
    void (*finish)(void *__this);
    bool (*supportsTouchscreen)(void *__this);
    bool (*hasIDEProfiler)(void *__this);
    bool (*supportsVibration)(void *__this);
    void (*vibrate)(void *__this, int ms);
    android_string_t (*getPlatformStringVar)(void *__this, int reserved);
    void (*showKeyboard)(void *__this, android_string_t *u0, int u1, bool set);
    void (*hideKeyboard)(void *__this);
    void (*updateTextBoxText)(void *__this, android_string_t *text);
    bool (*isKeyboardVisible)(void *__this);
    minecraft_login_info_t (*getLoginInformation)(void *__this);
    void (*setLoginInformation)(void *__this, minecraft_login_info_t *info);
    void (*clearSessionIDAndRefreshToken)(void *__this);
    void (*statsTrackData)(void *__this, android_string_t *u0, android_string_t *u1);
    void (*updateStatsUserData)(void *__this, android_string_t *u0, android_string_t *u1);
    uint64_t (*getAvailableMemory)(void *__this);
    android_vector_t (*getBroadcastAddresses)(void *__this);
} app_platform_vtable_0_9_0_t;

typedef struct {
    void (*__destroy0)(void *__this);
    void (*__destroy1)(void *__this);
    android_string_t (*getImagePath)(void *__this, android_string_t *resource_path, bool is_full);
    void (*loadPNG)(void *__this, image_data_0_9_0_t *image, android_string_t *resource_path, bool alpha);
    void (*loadTGA)(void *__this, image_data_0_9_0_t *image, android_string_t *resource_path);
    void (*playSound)(void *__this, android_string_t *resource_path, float volume, float pitch);
    void (*showDialog)(void *__this, int dialog_id);
    void (*createUserInput)(void *__this);
    int (*getUserInputStatus)(void *__this);
    android_vector_t (*getUserInput)(void *__this);
    android_string_t (*getDateString)(void *__this, int ms);
    int (*checkLicense)(void *__this);
    bool (*hasBuyButtonWhenInvalidLicense)(void *__this);
    void (*saveImage)(void *__this, android_string_t *resource_path, android_string_t *name, int width, int height);
    void (*uploadPlatformDependentData)(void *__this, int length, void *data);
    minecraft_asset_t (*readAssetFile)(void *__this, android_string_t *resource_path);
    void (*_tick)(void *__this);
    int (*getScreenWidth)(void *__this);
    int (*getScreenHeight)(void *__this);
    float (*getPixelsPerMillimeter)(void *__this);
    bool (*isNetworkEnabled)(void *__this, bool set);
    void (*openLoginWindow)(void *__this);
    bool (*isPowerVR)(void *__this);
    int (*getKeyFromKeyCode)(void *__this, int code, int meta, int dev_id);
    void (*buyGame)(void *__this);
    void (*finish)(void *__this);
    void (*swapBuffers)(void *__this);
    bool (*supportsTouchscreen)(void *__this);
    bool (*hasIDEProfiler)(void *__this);
    bool (*supportsVibration)(void *__this);
    void (*vibrate)(void *__this, int ms);
    android_string_t (*getPlatformStringVar)(void *__this, int reserved);
    void (*showKeyboard)(void *__this, android_string_t *u0, int u1, bool set);
    void (*hideKeyboard)(void *__this);
    void (*updateTextBoxText)(void *__this, android_string_t *text);
    bool (*isKeyboardVisible)(void *__this);
    minecraft_login_info_t (*getLoginInformation)(void *__this);
    void (*setLoginInformation)(void *__this, minecraft_login_info_t *info);
    void (*clearSessionIDAndRefreshToken)(void *__this);
    void (*statsTrackData)(void *__this, android_string_t *u0, android_string_t *u1);
    void (*captureScreen)(int width, int height, bool do_capture);
    uint64_t (*getAvailableMemory)(void *__this);
    android_vector_t (*getBroadcastAddresses)(void *__this);
    android_string_t (*getModelName)(void *__this);
} app_platform_vtable_0_10_0_t;

typedef struct {
    void (*__destroy0)(void *__this);
    void (*__destroy1)(void *__this);
    android_string_t (*getImagePath)(void *__this, android_string_t *resource_path, bool is_full);
    void (*loadPNG)(void *__this, image_data_0_9_0_t *image, android_string_t *resource_path, bool alpha);
    void (*loadTGA)(void *__this, image_data_0_9_0_t *image, android_string_t *resource_path);
    void (*savePNG)(void *__this, image_data_0_9_0_t *image, android_string_t *resource_path);
    int (*getKeyFromKeyCode)(void *__this, int code, int meta, int dev_id);
    void (*showKeyboard)(void *__this, android_string_t *u0, int u1, bool set);
    void (*hideKeyboard)(void *__this);
    void (*captureScreen)(void *__this, int width, int height, unsigned int px_width, bool do_capture);
    void (*swapBuffers)(void *__this);
    android_string_t *(*getSystemRegion)(void *__this);
    android_string_t (*getGraphicsVendor)(void *__this);
    android_string_t (*getGraphicsRenderer)(void *__this);
    android_string_t (*getGraphicsVersion)(void *__this);
    android_string_t (*getGraphicsExtensions)(void *__this);
    void (*pickImage)(void *__this, image_picking_callback_0_11_0_t *callback);
    void (*setSleepEnabled)(void *__this, bool set);
    android_string_t *(*getExternalStoragePath)(void *__this);
    android_string_t *(*getInternalStoragePath)(void *__this);
    void (*playSound)(void *__this, android_string_t *resource_path, float volume, float pitch);
    void (*showDialog)(void *__this, int);
    void (*createUserInput)(void *__this);
    int (*getUserInputStatus)(void *__this);
    android_vector_t (*getUserInput)(void *__this);
    void (*_tick)(void *__this);
    int (*getScreenWidth)(void *__this);
    int (*getScreenHeight)(void *__this);
    float (*getPixelsPerMillimeter)(void *__this);
    void (*openLoginWindow)(void *__this);
    void (*updateTextBoxText)(void *__this, android_string_t *text);
    bool (*isKeyboardVisible)(void *__this);
    minecraft_login_info_t (*getLoginInformation)(void *__this);
    void (*setLoginInformation)(void *__this, minecraft_login_info_t *info);
    void (*clearSessionIDAndRefreshToken)(void *__this);
    bool (*supportsVibration)(void *__this);
    void (*vibrate)(void *__this, int ms);
    minecraft_asset_t (*readAssetFile)(void *__this, android_string_t *resource_path);
    void (*listAssetFilesIn)(void *__this, android_string_t *, android_string_t *);
    android_string_t (*getDateString)(void *__this, int ms);
    int (*checkLicense)(void *__this);
    bool (*hasBuyButtonWhenInvalidLicense)(void *__this);
    void (*uploadPlatformDependentData)(void *__this, int length, void *data);
    bool (*isNetworkEnabled)(void *__this, bool set);
    bool (*isPowerVR)(void *__this);
    void (*buyGame)(void *__this);
    void (*finish)(void *__this);
    bool (*supportsTouchscreen)(void *__this);
    bool (*hasIDEProfiler)(void *__this);
    android_string_t (*getPlatformStringVar)(void *__this, int reserved);
    android_string_t (*getApplicationId)(void *__this);
    uint64_t (*getAvailableMemory)(void *__this);
    android_vector_t (*getBroadcastAddresses)(void *__this);
    android_string_t (*getModelName)(void *__this);
    android_string_t (*getDeviceId)(void *__this);
    android_string_t (*createUUID)(void *__this);
    bool (*isFirstSnoopLaunch)(void *__this);
    bool (*hasHardwareInformationChanged)(void *__this);
    bool (*isTablet)(void *__this);
    void (*registerUriListener)(void *__this, void *uri_listener);
    void (*unregisterUriListener)(void *__this, void *uri_listener);
} app_platform_vtable_0_11_0_t;

typedef struct {
    void (*__destroy0)(void *__this);
    void (*__destroy1)(void *__this);
    android_string_t (*getDataUrl)(void *__this);
    android_string_t (*getImagePath)(void *__this, android_string_t *resource_path, bool is_full);
    void (*loadPNG)(void *__this, image_data_0_9_0_t *image, android_string_t *resource_path, bool alpha);
    void (*loadTGA)(void *__this, image_data_0_9_0_t *image, android_string_t *resource_path);
    void (*savePNG)(void *__this, image_data_0_9_0_t *image, android_string_t *resource_path);
    int (*getKeyFromKeyCode)(void *__this, int code, int meta, int dev_id);
    void (*showKeyboard)(void *__this, android_string_t *u0, int u1, bool set, int flag);
    void (*hideKeyboard)(void *__this);
    void (*hideMousePointer)(void *__this);
    void (*showMousePointer)(void *__this);
    bool (*getPointerFocus)(void *__this);
    void (*setPointerFocus)(void *__this, bool set);
    void (*toggleSimulateTouchWithMouse)(void *__this);
    void (*captureScreen)(void *__this, int width, int height, unsigned int px_width, bool do_capture);
    void (*swapBuffers)(void *__this);
    android_string_t *(*getSystemRegion)(void *__this);
    android_string_t (*getGraphicsVendor)(void *__this);
    android_string_t (*getGraphicsRenderer)(void *__this);
    android_string_t (*getGraphicsVersion)(void *__this);
    android_string_t (*getGraphicsExtensions)(void *__this);
    void (*pickImage)(void *__this, image_picking_callback_0_11_0_t *callback);
    void (*setSleepEnabled)(void *__this, bool set);
    android_string_t *(*getExternalStoragePath)(void *__this);
    android_string_t *(*getInternalStoragePath)(void *__this);
    void (*showDialog)(void *__this, int);
    void (*createUserInput)(void *__this);
    int (*getUserInputStatus)(void *__this);
    android_vector_t (*getUserInput)(void *__this);
    void (*_tick)(void *__this);
    int (*getScreenWidth)(void *__this);
    int (*getScreenHeight)(void *__this);
    float (*getPixelsPerMillimeter)(void *__this);
    void (*openLoginWindow)(void *__this);
    void (*updateTextBoxText)(void *__this, android_string_t *text);
    bool (*isKeyboardVisible)(void *__this);
    minecraft_login_info_t (*getLoginInformation)(void *__this);
    void (*setLoginInformation)(void *__this, minecraft_login_info_t *info);
    void (*clearSessionIDAndRefreshToken)(void *__this);
    bool (*supportsVibration)(void *__this);
    void (*vibrate)(void *__this, int ms);
    minecraft_asset_t (*readAssetFile)(void *__this, android_string_t *resource_path);
    void (*listAssetFilesIn)(void *__this, android_string_t *, android_string_t *);
    android_string_t (*getDateString)(void *__this, int ms);
    int (*checkLicense)(void *__this);
    bool (*hasBuyButtonWhenInvalidLicense)(void *__this);
    void (*uploadPlatformDependentData)(void *__this, int length, void *data);
    bool (*isNetworkEnabled)(void *__this, bool set);
    bool (*isPowerVR)(void *__this);
    void (*buyGame)(void *__this);
    void (*finish)(void *__this);
    void (*launchUri)(void *__this, android_string_t *uri);
    bool (*useMetadataDrivenScreens)(void *__this);
    bool (*useXboxControlHelpers)(void *__this);
    bool (*useCenteredGUI)(void *__this);
    bool (*hasIDEProfiler)(void *__this);
    android_string_t (*getPlatformStringVar)(void *__this, int reserved);
    android_string_t (*getApplicationId)(void *__this);
    uint64_t (*getAvailableMemory)(void *__this);
    android_vector_t (*getBroadcastAddresses)(void *__this);
    android_string_t (*getModelName)(void *__this);
    android_string_t (*getDeviceId)(void *__this);
    android_string_t (*createUUID)(void *__this);
    bool (*isFirstSnoopLaunch)(void *__this);
    bool (*hasHardwareInformationChanged)(void *__this);
    bool (*isTablet)(void *__this);
    void (*registerUriListener)(void *__this, void *uri_listener);
    void (*unregisterUriListener)(void *__this, void *uri_listener);
    void (*setFullscreenMode)(void *__this, int mode);
    int (*getCaretPosition)(void *__this);
} app_platform_vtable_0_12_1_t;

typedef struct {
    void (*__destroy0)(void *__this);
    void (*__destroy1)(void *__this);
    android_string_t (*getDataUrl)(void *__this);
    android_string_t (*getImagePath)(void *__this, android_string_t *resource_path, bool is_full);
    void (*loadPNG)(void *__this, image_data_0_9_0_t *image, android_string_t *resource_path, bool alpha);
    void (*loadTGA)(void *__this, image_data_0_9_0_t *image, android_string_t *resource_path);
    void (*savePNG)(void *__this, image_data_0_9_0_t *image, android_string_t *resource_path);
    int (*getKeyFromKeyCode)(void *__this, int code, int meta, int dev_id);
    void (*showKeyboard)(void *__this, android_string_t *u0, int u1, bool set, bool set2, void *vec2);
    void (*hideKeyboard)(void *__this);
    float (*getKeyboardHeight)(void *__this);
    void (*hideMousePointer)(void *__this);
    void (*showMousePointer)(void *__this);
    bool (*getPointerFocus)(void *__this);
    void (*setPointerFocus)(void *__this, bool set);
    void (*toggleSimulateTouchWithMouse)(void *__this);
    void (*captureScreen)(void *__this, int width, int height, unsigned int px_width, bool do_capture);
    void (*swapBuffers)(void *__this);
    android_string_t *(*getSystemRegion)(void *__this);
    android_string_t (*getGraphicsVendor)(void *__this);
    android_string_t (*getGraphicsRenderer)(void *__this);
    android_string_t (*getGraphicsVersion)(void *__this);
    android_string_t (*getGraphicsExtensions)(void *__this);
    void (*pickImage)(void *__this, image_picking_callback_0_11_0_t *callback);
    void (*setSleepEnabled)(void *__this, bool set);
    android_string_t *(*getExternalStoragePath)(void *__this);
    android_string_t *(*getInternalStoragePath)(void *__this);
    android_string_t *(*getUserdataPath)(void *__this);
    void (*showDialog)(void *__this, int);
    void (*createUserInput)(void *__this);
    int (*getUserInputStatus)(void *__this);
    android_vector_t (*getUserInput)(void *__this);
    void (*_tick)(void *__this);
    int (*getScreenWidth)(void *__this);
    int (*getScreenHeight)(void *__this);
    float (*getPixelsPerMillimeter)(void *__this);
    void (*updateTextBoxText)(void *__this, android_string_t *text);
    bool (*isKeyboardVisible)(void *__this);
    bool (*supportsVibration)(void *__this);
    void (*vibrate)(void *__this, int ms);
    android_string_t (*getAssetFileFullPath)(void *__this, android_string_t *path);
    minecraft_asset_t (*readAssetFile)(void *__this, android_string_t *resource_path);
    void (*listAssetFilesIn)(void *__this, android_string_t *, android_string_t *);
    android_string_t (*getDateString)(void *__this, int ms);
    int (*checkLicense)(void *__this);
    bool (*hasBuyButtonWhenInvalidLicense)(void *__this);
    void (*uploadPlatformDependentData)(void *__this, int length, void *data);
    bool (*isNetworkEnabled)(void *__this, bool set);
    bool (*isPowerVR)(void *__this);
    void (*buyGame)(void *__this);
    void (*finish)(void *__this);
    void (*launchUri)(void *__this, android_string_t *uri);
    bool (*useMetadataDrivenScreens)(void *__this);
    bool (*useXboxControlHelpers)(void *__this);
    bool (*useCenteredGUI)(void *__this);
    bool (*useHeightScaleGUI)(void *__this);
    bool (*hasIDEProfiler)(void *__this);
    android_string_t (*getPlatformStringVar)(void *__this, int reserved);
    android_string_t (*getApplicationId)(void *__this);
    uint64_t (*getAvailableMemory)(void *__this);
    uint64_t (*getTotalMemory)(void *__this);
    android_vector_t (*getBroadcastAddresses)(void *__this);
    android_string_t (*getModelName)(void *__this);
    android_string_t (*getDeviceId)(void *__this);
    android_string_t (*createUUID)(void *__this);
    bool (*isFirstSnoopLaunch)(void *__this);
    bool (*hasHardwareInformationChanged)(void *__this);
    bool (*isTablet)(void *__this);
    void (*registerUriListener)(void *__this, void *uri_listener);
    void (*unregisterUriListener)(void *__this, void *uri_listener);
    void (*setFullscreenMode)(void *__this, int mode);
    bool (*isNetworkThrottled)(void *__this);
    void (*initWithActivity)(void *__this, void *activity);
} app_platform_vtable_0_13_0_t;

typedef struct {
    void (*__destroy0)(void *__this);
    void (*__destroy1)(void *__this);
    android_string_t (*getDataUrl)(void *__this);
    android_string_t (*getAlternateDataUrl)(void *__this);
    android_string_t (*getImagePath)(void *__this, android_string_t *resource_path, int location);
    void (*loadPNG)(void *__this, image_data_0_9_0_t *image, android_string_t *resource_path, int location);
    void (*loadTGA)(void *__this, image_data_0_9_0_t *image, android_string_t *resource_path, int location);
    void (*loadJPEG)(void *__this, image_data_0_9_0_t *image, android_string_t *resource_path, int location);
    int (*getKeyFromKeyCode)(void *__this, int code, int meta, int dev_id);
    void (*showKeyboard)(void *__this, android_string_t *u0, int u1, bool set, bool set2, void *vec2);
    void (*hideKeyboard)(void *__this);
    float (*getKeyboardHeight)(void *__this);
    void (*hideMousePointer)(void *__this);
    void (*showMousePointer)(void *__this);
    bool (*getPointerFocus)(void *__this);
    void (*setPointerFocus)(void *__this, bool set);
    void (*toggleSimulateTouchWithMouse)(void *__this);
    void (*swapBuffers)(void *__this);
    void (*discardBackbuffer)(void *__this);
    android_string_t *(*getSystemRegion)(void *__this);
    android_string_t (*getGraphicsVendor)(void *__this);
    android_string_t (*getGraphicsRenderer)(void *__this);
    android_string_t (*getGraphicsVersion)(void *__this);
    android_string_t (*getGraphicsExtensions)(void *__this);
    void (*pickImage)(void *__this, image_picking_callback_0_11_0_t *callback);
    void (*pickFile)(void *__this, void *settings);
    bool (*supportsFilePicking)(void *__this);
    void (*setSleepEnabled)(void *__this, bool set);
    android_string_t *(*getExternalStoragePath)(void *__this);
    android_string_t *(*getInternalStoragePath)(void *__this);
    android_string_t *(*getUserdataPath)(void *__this);
    android_string_t *(*getUserdataPathForLevels)(void *__this);
    void (*showDialog)(void *__this, int);
    void (*createUserInput)(void *__this);
    int (*getUserInputStatus)(void *__this);
    android_vector_t (*getUserInput)(void *__this);
    void (*_tick)(void *__this);
    int (*getScreenWidth)(void *__this);
    int (*getScreenHeight)(void *__this);
    void (*setScreenSize)(void *__this, int w, int h);
    float (*getPixelsPerMillimeter)(void *__this);
    void (*updateTextBoxText)(void *__this, android_string_t *text);
    bool (*isKeyboardVisible)(void *__this);
    bool (*supportsVibration)(void *__this);
    void (*vibrate)(void *__this, int ms);
    android_string_t (*getAssetFileFullPath)(void *__this, android_string_t *path);
    minecraft_asset_t (*readAssetFile)(void *__this, android_string_t *resource_path);
    void (*listAssetFilesIn)(void *__this, android_string_t *, android_string_t *);
    android_string_t (*getDateString)(void *__this, int ms);
    int (*checkLicense)(void *__this);
    bool (*hasBuyButtonWhenInvalidLicense)(void *__this);
    void (*uploadPlatformDependentData)(void *__this, int length, void *data);
    bool (*isNetworkEnabled)(void *__this, bool set);
    bool (*isPowerVR)(void *__this);
    void (*buyGame)(void *__this);
    void (*finish)(void *__this);
    void (*launchUri)(void *__this, android_string_t *uri);
    bool (*useMetadataDrivenScreens)(void *__this);
    bool (*useXboxControlHelpers)(void *__this);
    bool (*useCenteredGUI)(void *__this);
    int (*getPlatformType)(void *__this);
    int (*getScreenType)(void *__this);
    bool (*hasIDEProfiler)(void *__this);
    android_string_t (*getPlatformStringVar)(void *__this, int reserved);
    android_string_t (*getApplicationId)(void *__this);
    uint64_t (*getAvailableMemory)(void *__this);
    uint64_t (*getTotalMemory)(void *__this);
    android_vector_t (*getBroadcastAddresses)(void *__this);
    android_string_t (*getModelName)(void *__this);
    android_string_t (*getDeviceId)(void *__this);
    android_string_t (*createUUID)(void *__this);
    bool (*isFirstSnoopLaunch)(void *__this);
    bool (*hasHardwareInformationChanged)(void *__this);
    bool (*isTablet)(void *__this);
    void (*registerUriListener)(void *__this, void *uri_listener);
    void (*registerUriListener2)(void *__this, android_string_t *str, void *uri_listener);
    void (*unregisterUriListener)(void *__this, void *uri_listener);
    void (*notifyUriListeners)(void *__this, void *activation_uri);
    void (*notifyUriListenerRegistrationDone)(void *__this);
    void (*setFullscreenMode)(void *__this, int mode);
    bool (*isNetworkThrottled)(void *__this);
    void (*collectGraphicsHardwareDetails)(void *__this);
    int (*getEdition)(void *__this);
    void (*_notifyUriListeners)(void *__this, void *activation_uri, bool b);
    android_string_t *(*getPlatformTempPath)(void *__this);
    void (*initWithActivity)(void *__this, void *activity);
} app_platform_vtable_0_14_0_t;

typedef struct {
    void (*__destroy0)(void *__this);
    void (*__destroy1)(void *__this);
    android_string_t (*getDataUrl)(void *__this);
    android_string_t (*getPackagePath)(void *__this);
    void (*loadPNG)(void *__this, image_data_0_9_0_t *image, android_string_t *resource_path);
    void (*loadTGA)(void *__this, image_data_0_9_0_t *image, android_string_t *resource_path);
    void (*loadJPEG)(void *__this, image_data_0_9_0_t *image, android_string_t *resource_path);
    int (*getKeyFromKeyCode)(void *__this, int code, int meta, int dev_id);
    void (*showKeyboard)(void *__this, android_string_t *u0, int u1, bool set, bool set2, void *vec2);
    void (*hideKeyboard)(void *__this);
    bool (*isFullScreenKeyboard)(void *__this);
    float (*getKeyboardHeight)(void *__this);
    void (*hideMousePointer)(void *__this);
    void (*showMousePointer)(void *__this);
    bool (*getPointerFocus)(void *__this);
    void (*setPointerFocus)(void *__this, bool set);
    void (*toggleSimulateTouchWithMouse)(void *__this);
    void (*swapBuffers)(void *__this);
    void (*discardBackbuffer)(void *__this);
    android_string_t *(*getSystemRegion)(void *__this);
    android_string_t (*getGraphicsVendor)(void *__this);
    android_string_t (*getGraphicsRenderer)(void *__this);
    android_string_t (*getGraphicsVersion)(void *__this);
    android_string_t (*getGraphicsExtensions)(void *__this);
    void (*pickImage)(void *__this, image_picking_callback_0_11_0_t *callback);
    void (*pickFile)(void *__this, void *settings);
    bool (*supportsFilePicking)(void *__this);
    void (*pushNotificationReceived)(void *__this, void *message);
    void *(*createHolographicPlatform)(void *__this);
    void *(*createAndroidLaunchIntent)(void *__this);
    void (*updateLocalization)(void *__this, android_string_t *loc);
    void (*setSleepEnabled)(void *__this, bool set);
    android_string_t *(*getExternalStoragePath)(void *__this);
    android_string_t *(*getInternalStoragePath)(void *__this);
    android_string_t *(*getUserdataPath)(void *__this);
    android_string_t *(*getUserdataPathForLevels)(void *__this);
    android_string_t (*getApiEnvironmentPath)(void *__this);
    void (*showDialog)(void *__this, int);
    void (*createUserInput)(void *__this);
    int (*getUserInputStatus)(void *__this);
    android_vector_t (*getUserInput)(void *__this);
    void (*_tick)(void *__this);
    int (*getScreenWidth)(void *__this);
    int (*getScreenHeight)(void *__this);
    void (*setScreenSize)(void *__this, int w, int h);
    void (*setWindowSize)(void *__this, int w, int h);
    void (*setWindowText)(void *__this, android_string_t *text);
    float (*getPixelsPerMillimeter)(void *__this);
    void (*updateTextBoxText)(void *__this, android_string_t *text);
    bool (*isKeyboardVisible)(void *__this);
    bool (*supportsVibration)(void *__this);
    void (*vibrate)(void *__this, int ms);
    android_string_t (*getAssetFileFullPath)(void *__this, android_string_t *path);
    minecraft_asset_t (*readAssetFile)(void *__this, android_string_t *resource_path);
    minecraft_asset_t (*readAssetFileZipped)(void *__this, android_string_t *p1, android_string_t *p2);
    void (*listAssetFilesIn)(void *__this, android_string_t *, android_string_t *);
    android_string_t (*getDateString)(void *__this, int ms);
    int (*checkLicense)(void *__this);
    bool (*hasBuyButtonWhenInvalidLicense)(void *__this);
    void (*uploadPlatformDependentData)(void *__this, int length, void *data);
    bool (*isNetworkEnabled)(void *__this, bool set);
    bool (*isPowerVR)(void *__this);
    void (*buyGame)(void *__this);
    void (*finish)(void *__this);
    void (*launchUri)(void *__this, android_string_t *uri);
    bool (*useMetadataDrivenScreens)(void *__this);
    bool (*useXboxControlHelpers)(void *__this);
    bool (*useCenteredGUI)(void *__this);
    int (*getPlatformType)(void *__this);
    int (*setControllerType)(void *__this, int type);
    int (*getControllerType)(void *__this);
    bool (*hasIDEProfiler)(void *__this);
    android_string_t (*getPlatformStringVar)(void *__this, int reserved);
    android_string_t (*getApplicationId)(void *__this);
    uint64_t (*getAvailableMemory)(void *__this);
    uint64_t (*getTotalMemory)(void *__this);
    android_vector_t (*getBroadcastAddresses)(void *__this);
    android_vector_t (*getIPAddresses)(void *__this);
    android_string_t (*getModelName)(void *__this);
    android_string_t (*getDeviceId)(void *__this);
    android_string_t (*createUUID)(void *__this);
    bool (*isFirstSnoopLaunch)(void *__this);
    bool (*hasHardwareInformationChanged)(void *__this);
    bool (*isTablet)(void *__this);
    void (*registerUriListener)(void *__this, void *uri_listener);
    void (*registerUriListener2)(void *__this, android_string_t *str, void *uri_listener);
    void (*unregisterUriListener)(void *__this, void *uri_listener);
    void (*notifyUriListeners)(void *__this, void *activation_uri);
    void (*notifyUriListenerRegistrationDone)(void *__this);
    void (*setFullscreenMode)(void *__this, int mode);
    bool (*isNetworkThrottled)(void *__this);
    void (*collectGraphicsHardwareDetails)(void *__this);
    int (*getEdition)(void *__this);
    bool (*realmsBeta)(void *__this);
    bool (*isFireTV)(void *__this);
    int (*getDefaultInputMode)(void *__this);
    void (*_notifyUriListeners)(void *__this, void *activation_uri, bool b);
    int (*getPlatformDpi)(void *__this);
    int (*getPlatformUIScalingRules)(void *__this);
    android_string_t *(*getPlatformTempPath)(void *__this);
    void (*initWithActivity)(void *__this, void *activity);
} app_platform_vtable_0_15_0_t;

typedef struct {
    void (*__destroy0)(void *__this);
    void (*__destroy1)(void *__this);
    android_string_t (*getDataUrl)(void *__this);
    android_string_t (*getAlternateDataUrl)(void *__this);
    android_string_t (*getPackagePath)(void *__this);
    void (*loadPNG)(void *__this, void *image, android_string_t *resource_path);
    void (*loadTGA)(void *__this, void *image, android_string_t *resource_path);
    void (*loadJPEG)(void *__this, void *image, android_string_t *resource_path);
    int (*getKeyFromKeyCode)(void *__this, int code, int meta, int dev_id);
    void (*showKeyboard)(void *__this, android_string_t *u0, int u1, bool set, bool set2, void *vec2);
    void (*hideKeyboard)(void *__this);
    bool (*isFullScreenKeyboard)(void *__this);
    float (*getKeyboardHeight)(void *__this);
    void (*hideMousePointer)(void *__this);
    void (*showMousePointer)(void *__this);
    bool (*getPointerFocus)(void *__this);
    void (*setPointerFocus)(void *__this, bool set);
    void (*toggleSimulateTouchWithMouse)(void *__this);
    void (*swapBuffers)(void *__this);
    void (*discardBackbuffer)(void *__this);
    android_string_t *(*getSystemRegion)(void *__this);
    android_string_t (*getGraphicsVendor)(void *__this);
    android_string_t (*getGraphicsRenderer)(void *__this);
    android_string_t (*getGraphicsVersion)(void *__this);
    android_string_t (*getGraphicsExtensions)(void *__this);
    void (*pickImage)(void *__this, image_picking_callback_0_11_0_t *callback);
    void (*pickFile)(void *__this, void *settings);
    bool (*supportsFilePicking)(void *__this);
    void (*pushNotificationReceived)(void *__this, void *message);
    void *(*createHolographicPlatform)(void *__this);
    void *(*createAndroidLaunchIntent)(void *__this);
    void (*updateLocalization)(void *__this, android_string_t *loc);
    void (*setSleepEnabled)(void *__this, bool set);
    android_string_t *(*getExternalStoragePath)(void *__this);
    android_string_t *(*getInternalStoragePath)(void *__this);
    android_string_t *(*getUserdataPath)(void *__this);
    android_string_t *(*getUserdataPathForLevels)(void *__this);
    android_string_t (*getApiEnvironmentPath)(void *__this);
    void (*showDialog)(void *__this, int);
    void (*createUserInput)(void *__this);
    int (*getUserInputStatus)(void *__this);
    android_vector_t (*getUserInput)(void *__this);
    void (*_tick)(void *__this);
    int (*getScreenWidth)(void *__this);
    int (*getScreenHeight)(void *__this);
    void (*setScreenSize)(void *__this, int w, int h);
    void (*setWindowSize)(void *__this, int w, int h);
    void (*setWindowText)(void *__this, android_string_t *text);
    float (*getPixelsPerMillimeter)(void *__this);
    void (*updateTextBoxText)(void *__this, android_string_t *text);
    bool (*isKeyboardVisible)(void *__this);
    bool (*supportsVibration)(void *__this);
    void (*vibrate)(void *__this, int ms);
    android_string_t (*getAssetFileFullPath)(void *__this, android_string_t *path);
    minecraft_asset_t (*readAssetFile)(void *__this, android_string_t *resource_path);
    minecraft_asset_t (*readAssetFileZipped)(void *__this, android_string_t *p1, android_string_t *p2);
    void (*listAssetFilesIn)(void *__this, android_string_t *, android_string_t *);
    android_string_t (*getDateString)(void *__this, int ms);
    int (*checkLicense)(void *__this);
    bool (*hasBuyButtonWhenInvalidLicense)(void *__this);
    void (*uploadPlatformDependentData)(void *__this, int length, void *data);
    bool (*isNetworkEnabled)(void *__this, bool set);
    bool (*isPowerVR)(void *__this);
    void (*buyGame)(void *__this);
    void (*finish)(void *__this);
    void (*launchUri)(void *__this, android_string_t *uri);
    bool (*useMetadataDrivenScreens)(void *__this);
    bool (*useXboxControlHelpers)(void *__this);
    bool (*useCenteredGUI)(void *__this);
    int (*getPlatformType)(void *__this);
    int (*setControllerType)(void *__this, int type);
    int (*getControllerType)(void *__this);
    bool (*hasIDEProfiler)(void *__this);
    android_string_t (*getPlatformStringVar)(void *__this, int reserved);
    android_string_t (*getApplicationId)(void *__this);
    uint64_t (*getAvailableMemory)(void *__this);
    uint64_t (*getTotalMemory)(void *__this);
    android_vector_t (*getBroadcastAddresses)(void *__this);
    android_vector_t (*getIPAddresses)(void *__this);
    android_string_t (*getModelName)(void *__this);
    android_string_t (*getDeviceId)(void *__this);
    android_string_t (*createUUID)(void *__this);
    bool (*isFirstSnoopLaunch)(void *__this);
    bool (*hasHardwareInformationChanged)(void *__this);
    bool (*isTablet)(void *__this);
    void (*registerUriListener)(void *__this, void *uri_listener);
    void (*registerUriListener2)(void *__this, android_string_t *str, void *uri_listener);
    void (*unregisterUriListener)(void *__this, void *uri_listener);
    void (*notifyUriListeners)(void *__this, void *activation_uri);
    void (*notifyUriListenerRegistrationDone)(void *__this);
    void (*setFullscreenMode)(void *__this, int mode);
    bool (*isNetworkThrottled)(void *__this);
    void (*collectGraphicsHardwareDetails)(void *__this);
    int (*getEdition)(void *__this);
    bool (*realmsBeta)(void *__this);
    bool (*isFireTV)(void *__this);
    int (*getDefaultInputMode)(void *__this);
    void (*_notifyUriListeners)(void *__this, void *activation_uri, bool b);
    int (*getPlatformDpi)(void *__this);
    int (*getPlatformUIScalingRules)(void *__this);
    android_string_t *(*getPlatformTempPath)(void *__this);
    void (*initWithActivity)(void *__this, void *activity);
} app_platform_vtable_0_15_1_t;

typedef struct {
    void *__destroy0;
    void *__destroy1;
    void *getDataUrl;
    void *getAlternateDataUrl;
    void *getPackagePath;
    void *loadPNG;
    void *loadTGA;
    void *loadJPEG;
    void *getKeyFromKeyCode;
    void *showKeyboard;
    void *hideKeyboard;
    void *isFullScreenKeyboard;
    void *getKeyboardHeight;
    void *hideMousePointer;
    void *showMousePointer;
    void *getPointerFocus;
    void *setPointerFocus;
    void *toggleSimulateTouchWithMouse;
    void *_fireAppFocusLost;
    void *_fireAppFocusGained;
    void *_fireAppConfigurationChanged;
    void *_fireAppPaused;
    void *swapBuffers;
    void *discardBackbuffer;
    void *getSystemRegion;
    void *getGraphicsTearingSupport;
    void *pickImage;
    void *pickFile;
    void *supportsFilePicking;
    void *pushNotificationReceived;
    void *createHolographicPlatform;
    void *createAndroidLaunchIntent;
    void *updateLocalization;
    void *setSleepEnabled;
    void *getExternalStoragePath;
    void *getInternalStoragePath;
    void *getUserdataPath;
    void *getUserdataPathForLevels;
    void *getApiEnvironmentPath;
    void *showDialog;
    void *createUserInput;
    void *getUserInputStatus;
    void *getUserInput;
    void *_tick;
    void *getScreenWidth;
    void *getScreenHeight;
    void *setScreenSize;
    void *setWindowSize;
    void *setWindowText;
    void *getPixelsPerMillimeter;
    void *updateTextBoxText;
    void *isKeyboardVisible;
    void *supportsVibration;
    void *vibrate;
    void *getAssetFileFullPath;
    void *readAssetFile;
    void *readAssetFileZipped;
    void *listAssetFilesIn;
    void *getDateString;
    void *checkLicense;
    void *hasBuyButtonWhenInvalidLicense;
    void *uploadPlatformDependentData;
    void *isNetworkEnabled;
    void *buyGame;
    void *finish;
    void *launchUri;
    void *useXboxControlHelpers;
    void *useCenteredGUI;
    void *showPointMenuCursor;
    void *getPlatformType;
    void *setControllerType;
    void *getControllerType;
    void *hasIDEProfiler;
    void *getPlatformStringVar;
    void *getApplicationId;
    void *getAvailableMemory;
    void *getTotalMemory;
    void *getBroadcastAddresses;
    void *getIPAddresses;
    void *getModelName;
    void *getDeviceId;
    void *createUUID;
    void *isFirstSnoopLaunch;
    void *hasHardwareInformationChanged;
    void *isTablet;
    void *registerUriListener;
    void *registerUriListener_2;
    void *unregisterUriListener;
    void *notifyUriListeners;
    void *notifyUriListenerRegistrationDone;
    void *setFullscreenMode;
    void *isNetworkThrottled;
    void *collectGraphicsHardwareDetails;
    void *getEdition;
    void *realmsBeta;
    void *isFireTV;
    void *getDefaultInputMode;
    void *_notifyUriListeners;
    void *getPlatformDpi;
    void *getPlatformUIScalingRules;
    void *getPlatformTempPath;
    void *initWithActivity;
    void *slot_102;
    void *slot_103;
    void *__destroy104;
} app_platform_vtable_0_15_90_0_t;

typedef struct {
    void *__destroy0;
    void *__destroy1;
    void *getDataUrl;
    void *getAlternateDataUrl;
    void *getPackagePath;
    void *loadPNG;
    void *loadTGA;
    void *loadJPEG;
    void *getKeyFromKeyCode;
    void *showKeyboard;
    void *hideKeyboard;
    void *isFullScreenKeyboard;
    void *getKeyboardHeight;
    void *hideMousePointer;
    void *showMousePointer;
    void *getPointerFocus;
    void *setPointerFocus;
    void *toggleSimulateTouchWithMouse;
    void *_fireLowMemory;
    void *_fireAppSuspended;
    void *_fireAppResumed;
    void *_fireAppFocusLost;
    void *_fireAppFocusGained;
    void *_fireAppTerminated;
    void *_fireAppConfigurationChanged;
    void *_fireAppPaused;
    void *swapBuffers;
    void *discardBackbuffer;
    void *getSystemRegion;
    void *getGraphicsTearingSupport;
    void *pickImage;
    void *pickFile;
    void *supportsFilePicking;
    void *pushNotificationReceived;
    void *createHolographicPlatform;
    void *createAndroidLaunchIntent;
    void *updateLocalization;
    void *setSleepEnabled;
    void *getExternalStoragePath;
    void *getInternalStoragePath;
    void *getUserdataPath;
    void *getUserdataPathForLevels;
    void *getApiEnvironmentPath;
    void *showDialog;
    void *createUserInput;
    void *getUserInputStatus;
    void *getUserInput;
    void *getScreenWidth;
    void *getScreenHeight;
    void *setScreenSize;
    void *setWindowSize;
    void *setWindowText;
    void *getPixelsPerMillimeter;
    void *updateTextBoxText;
    void *isKeyboardVisible;
    void *supportsVibration;
    void *vibrate;
    void *getAssetFileFullPath;
    void *readAssetFile;
    void *readAssetFileZipped;
    void *listAssetFilesIn;
    void *getDateString;
    void *checkLicense;
    void *hasBuyButtonWhenInvalidLicense;
    void *uploadPlatformDependentData;
    void *isNetworkEnabled;
    void *buyGame;
    void *finish;
    void *launchUri;
    void *useXboxControlHelpers;
    void *useCenteredGUI;
    void *showPointMenuCursor;
    void *getPlatformType;
    void *setControllerType;
    void *getControllerType;
    void *hasIDEProfiler;
    void *getPlatformStringVar;
    void *getApplicationId;
    void *getAvailableMemory;
    void *getTotalMemory;
    void *getBroadcastAddresses;
    void *getIPAddresses;
    void *getModelName;
    void *getDeviceId;
    void *createUUID;
    void *isFirstSnoopLaunch;
    void *hasHardwareInformationChanged;
    void *isTablet;
    void *registerUriListener;
    void *registerUriListener_2;
    void *unregisterUriListener;
    void *notifyUriListeners;
    void *notifyUriListenerRegistrationDone;
    void *setFullscreenMode;
    void *isNetworkThrottled;
    void *collectGraphicsHardwareDetails;
    void *getEdition;
    void *realmsBeta;
    void *isFireTV;
    void *getDefaultInputMode;
    void *_notifyUriListeners;
    void *getPlatformDpi;
    void *getPlatformUIScalingRules;
    void *getPlatformTempPath;
    void *initWithActivity;
    void *slot_105;
} app_platform_vtable_0_16_0_t;

extern app_platform_vtable_0_9_0_t platform_vtable_0_9_0;
extern app_platform_vtable_0_10_0_t platform_vtable_0_10_0;
extern app_platform_vtable_0_11_0_t platform_vtable_0_11_0;
extern app_platform_vtable_0_12_1_t platform_vtable_0_12_1;
extern app_platform_vtable_0_13_0_t platform_vtable_0_13_0;
extern app_platform_vtable_0_14_0_t platform_vtable_0_14_0;
extern app_platform_vtable_0_15_0_t platform_vtable_0_15_0;
extern app_platform_vtable_0_15_1_t platform_vtable_0_15_1;
extern app_platform_vtable_0_15_90_0_t platform_vtable_0_15_90_0;
extern app_platform_vtable_0_16_0_t platform_vtable_0_16_0;